---
driver:
  name: dokken
  chef_version: 12.5.1
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
#- name: ubuntu-14.04
#  driver:
#    image: ubuntu:14.04
#    intermediate_instructions:
#      - RUN /usr/bin/apt-get update
#      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y
#      - RUN mkdir /var/lock/apache2
#    pid_one_command: /sbin/init
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
- name: centos-6.8
  driver:
    image: centos:6.8
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: centos-7.2
  driver:
    image: centos:7.2.1511
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: oracle-6.8
  driver:
    image: oraclelinux:6.8
- name: oracle-7.2
  driver:
    image: oraclelinux:7.2
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd

suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[apache2]
    - recipe[apache2::mod_ssl]
    - recipe[apache-hardening::default]

  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-apache-hardening.git
