---
driver:
  name: vagrant
provisioner:
  name: chef_solo
#  require_chef_omnibus: 12.5
#  test_repo_uri: https://github.com/dev-sec/tests-apache-hardening.git
platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu/precise64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/precise64/versions/20160527.0.0/providers/virtualbox.box
- name: ubuntu-14.04
  driver_config:
    box: ubuntu/trusty64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160601.0.0/providers/virtualbox.box
- name: ubuntu-16.04
  driver_config:
    box: ubuntu/xenial64
    box_url: https://atlas.hashicorp.com/ubuntu/boxes/xenial64/versions/20160531.0.0/providers/virtualbox.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.7
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box
- name: centos-7.2
  driver_config:
    box: opscode-centos-7.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box
- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box
- name: oracle-6.5
  driver_config:
    box: oracle-6.5
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box
- name: debian-7
  driver_config:
    box: debian/wheezy64
    box_url: https://atlas.hashicorp.com/debian/boxes/wheezy64/versions/7.10.0/providers/virtualbox.box
- name: debian-8
  driver_config:
    box: debian/jessie64
    box_url: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.4.0/providers/virtualbox.box
verifier:
  name: inspec
  sudo: true
suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[apache2]
    - recipe[apache2::mod_ssl]
    - recipe[apache-hardening::default]
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-apache-hardening.git
